# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PruebaKYDrawer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'KYDrawerController'

  # Pods for PruebaKYDrawer

  target 'PruebaKYDrawerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PruebaKYDrawerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
